Drop computed but unused offset from GetPosixPerms()
The computed but unused offset variable in GetPosixPerms() results in a
new warning when compiling with gcc 16.

../win32.cc: In member function 'void* NTSecurity::GetPosixPerms(const char*, PSID, PSID, mode_t, SECURITY_DESCRIPTOR&, acl_t&)':
../win32.cc:38:9: error: variable 'offset' set but not used [-Werror=unused-but-set-variable=]