Fix mismatched-new-delete warning in mkwslsymlink()
Fix mismatched-new-delete warning (new in gcc 12) in mkwslsymlink(),
introduced by 93b295d6

> ../mklink2.cc: In function 'int mkwslsymlink(const char*, const char*)':
> ../mklink2.cc:194:10: error: 'void operator delete(void*)' called on pointer returned from a mismatched allocation function [-Werror=mismatched-new-delete]
> ../mklink2.cc:178:115: note: returned from 'void* operator new [](std::size_t)'