Fix -Werror=unused-const-variable error seen with gcc 6
sha2.c:199:24: error: 'sha224_initial_hash_value' defined but not used [-Werror=unused-const-variable=]